export const CATEGORY_GROUP_IMAGES: Record<string, string> = {
  "Moda e Estilo": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/moda.png",
  "Tecnologia e Eletrônicos": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/Gemini_Generated_Image_yjorh6yjorh6yjor.png",
  "Casa e Decoração": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/casaedecoracao.png",
  "Eletrodomésticos": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/eletrodomesticos.png",
  "Beleza e Cuidados Pessoais": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/perfumes.png",
  "Bebés e Crianças": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/bebeecriancas.png",
  "Ferramentas e Construção": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/ferramentasdeconstrucao.png",
  "Automóveis e Motos": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/Automoveisemotos.png",
  "Papelaria e Escritório": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/papelariaeescritorio.png",
  "Esportes e Lazer": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/Esportes_e_Lazer-removebg-preview.png",
  "Supermercado e Alimentos": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/groceries.png",
  "Saúde e Bem-estar": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/saude.png",
  "Animais de Estimação": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/Pets.png",
  "Entretenimento e Cultura": "https://kxvyveizgrnieetbttjx.supabase.co/storage/v1/object/public/Banners%20and%20Logos/Banners/previewscategoria/Entretenimento%20e%20cultura.png",
};