// This file is automatically generated. Do not edit it directly.
import { createClient as createSupabaseClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kxvyveizgrnieetbttjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dnl2ZWl6Z3JuaWVldGJ0dGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNDU5NTYsImV4cCI6MjA3NjcyMTk1Nn0.d8O0y0emx4ERKvgkotyNw_Krv8n3KYjZhUnZMwujFq8";

// Create and export the supabase client
export const supabase = createSupabaseClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);